package edu.wpi.first.shuffleboard.plugin.networktables;

/**
 * Autogenerated version class containing the version of the networktables plugin.
 *
 * <p><strong>DO NOT MODIFY THIS CLASS</strong>
 */
public final class NetworktablesPluginVersion {

  /**
   * The version of the networktables plugin.
   */
  public static final String VERSION = "1.5.0";

  private NetworktablesPluginVersion() {
    throw new UnsupportedOperationException();
  }
}