package edu.wpi.first.shuffleboard.plugin.powerup;

/**
 * Autogenerated version class containing the version of the powerup plugin.
 *
 * <p><strong>DO NOT MODIFY THIS CLASS</strong>
 */
public final class PowerupPluginVersion {

  /**
   * The version of the powerup plugin.
   */
  public static final String VERSION = "1.5.0";

  private PowerupPluginVersion() {
    throw new UnsupportedOperationException();
  }
}