package edu.wpi.first.shuffleboard.plugin.base;

/**
 * Autogenerated version class containing the version of the base plugin.
 *
 * <p><strong>DO NOT MODIFY THIS CLASS</strong>
 */
public final class BasePluginVersion {

  /**
   * The version of the base plugin.
   */
  public static final String VERSION = "1.5.0";

  private BasePluginVersion() {
    throw new UnsupportedOperationException();
  }
}