package edu.wpi.first.shuffleboard.plugin.cameraserver;

/**
 * Autogenerated version class containing the version of the CameraServer plugin.
 *
 * <p><strong>DO NOT MODIFY THIS CLASS</strong>
 */
public final class CameraServerPluginVersion {

  /**
   * The version of the CameraServer plugin.
   */
  public static final String VERSION = "1.5.0";

  private CameraServerPluginVersion() {
    throw new UnsupportedOperationException();
  }
}