package edu.wpi.first.shuffleboard.plugin.cameraserver;

/**
 * Autogenerated version class containing the version of the cameraserver plugin.
 *
 * <p><strong>DO NOT MODIFY THIS CLASS</strong>
 */
public final class CameraserverPluginVersion {

  /**
   * The version of the cameraserver plugin.
   */
  public static final String VERSION = "1.5.0";

  private CameraserverPluginVersion() {
    throw new UnsupportedOperationException();
  }
}