name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact-name: Win32
            architecture: x86
          - os: windows-latest
            artifact-name: Win64
            architecture: x64
          - os: macos-latest
            artifact-name: macOS
            architecture: x64
          - os: ubuntu-latest
            artifact-name: Linux
            architecture: x64

    name: "Build - ${{ matrix.artifact-name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: ${{ matrix.architecture }}

      - uses: wpilibsuite/import-signing-certificate@v1
        with:
          certificate-data: ${{ secrets.APPLE_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          keychain-password: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
        if: |
          (matrix.artifact-name == 'macOS') && (github.repository_owner == 'wpilibsuite') &&
          (startsWith(github.ref, 'refs/heads/') || startsWith(github.ref, 'refs/tags/v'))

      - name: Build with Gradle
        run: ./gradlew build -PbuildServer -PdeveloperID=${{ secrets.APPLE_DEVELOPER_ID }}
        if: ${{ !github.repository_owner == 'wpilibsuite' || !startsWith(github.ref, 'refs/tags/v') }}

      - name: Build with Gradle (Release)
        run: ./gradlew build -PbuildServer -PreleaseMode -PdeveloperID=${{ secrets.APPLE_DEVELOPER_ID }}
        if: ${{ github.repository_owner == 'wpilibsuite' && startsWith(github.ref, 'refs/tags/v') }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact-name }}
          path: build/allOutputs

  combine:
    runs-on: ubuntu-latest
    needs: build
    name: "Combine"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/download-artifact@v2
        with:
          path: build/allOutputs

      - name: Flatten Artifacts
        run: |
          rsync -a --delete --remove-source-files build/allOutputs/*/* build/allOutputs
          find build/allOutputs -type d -empty -delete

      - name: Combine (PR)
        run: ./gradlew publish -PbuildServer -PprCombinePublish
        if: |
          (github.repository_owner != 'wpilibsuite') ||
          (github.ref != 'refs/heads/master' && !startsWith(github.ref, 'refs/tags/v'))

      - name: Combine (Master)
        run: ./gradlew publish -PbuildServer
        if: ${{ github.repository_owner == 'wpilibsuite' && github.ref == 'refs/heads/master' }}
        env:
          RUN_AZURE_ARTIFACTORY_RELEASE: 'TRUE'
          ARTIFACTORY_PUBLISH_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PUBLISH_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Combine (Release)
        run: ./gradlew publish -PbuildServer -PreleaseMode
        if: ${{ github.repository_owner == 'wpilibsuite' && startsWith(github.ref, 'refs/tags/v') }}
        env:
          RUN_AZURE_ARTIFACTORY_RELEASE: 'TRUE'
          ARTIFACTORY_PUBLISH_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PUBLISH_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - uses: actions/upload-artifact@v2
        with:
          name: "Maven"
          path: ~/releases
